= veracode-gradle-plugin
:toc:

Veracode Gradle Plugin that automates Veracode application security scanning activities.

It helps perform the following tasks:

* Perform Veracode submissions for applications.
* Scan results for flaws.

== Pre-Requisites

* Veracode account & application to perform scanning.
* Veracode Java API JAR file (copy to `buildSrc/lib` directory).
The https://tools.veracode.com/integrations/API-Wrappers/Java/bin/VeracodeJavaAPI.zip[zip file] is found in the https://analysiscenter.veracode.com/auth/helpCenter/api/c_about_wrappers.html[documentation] from Veracode's website.
* JDK 7+ is a requirement for the Veracode Java API.

== Getting Started

=== Build the plugin

* Clone project:

----
git clone https://github.com/calgaryscientific/veracode-gradle-plugin
cd veracode-gradle-plugin
mkdir lib
----

* Copy the `VeracodeJavaAPI.jar` (from Veracode) to the newly created `lib` directory.

* Run `gradle uploadArchives` to build the plugin and publish it to `mavenLocal()`.

=== Use the plugin

* Add the following properties to the project’s `gradle.properties` and edit its contents to setup Veracode credentials.
+
.Required gradle.properties
----
veracodeUseAPICredentials=false
veracodeUsername=xxx
veracodePassword=xxx
veracodeID=xxx
veracodeKey=xxx
----
+
NOTE: Optionally, the Veracode credentials properties can be placed in the `~/.gradle/gradle.properties` file.
+
NOTE: There is a sample `gradle.properties` file that can be used as a base: `sample-gradle.properties`.

* Add the contents of the `sample-build.gradle` file to the project’s `build.gradle` file:
+
----
apply plugin: 'groovy'

buildscript {
    apply plugin: 'groovy'
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath files('./lib/VeracodeJavaAPI.jar')
        classpath 'com.calgaryscientific.gradle:veracodePlugin:1.0-SNAPSHOT'
    }
}
apply plugin: 'com.calgaryscientific.gradle.veracode'

veracodeCredentials {
    username = "$veracodeUsername"
    password = "$veracodePassword"
    id = "$veracodeID"
    key = "$veracodeKey"
}
----

* Copy the `VeracodeJavaAPI.jar` (from Veracode) to a newly created `lib` directory.

* Execute `gradle tasks` to see available tasks.

* Execute `gradle veracodeGetAppList` to see available applications and their `app_id`.

=== Veracode App ID

Most Veracode commands require passing an `app_id`.
This value can be passed as a gradle _property_ on the command line.
For example: `gradle veracodeGetAppInfo -P app_id=123`

Additionally, the app_id can be defined in the `gradle.properties` file so it is no longer required.

The same holds true for any other property, including `sandbox_id`.

== Typical Veracode Submission Workflow

The sequence of tasks to perform Veracode Scans for an application involves:

* Download the artifacts for the application to scan (manual).

* Run `generateToUpload`: Prepare JAR files installed by the application for upload.
This involves stripping timestamp information.
TODO: rename task to "prepareUpload"?

* Run `veracodeCreateBuild`: Create a new veracode build for the application to scan.

* Run `veracodeUploadFile`: Upload files to Veracode.
This process will upload each file prepared by `generateToUpload` to Veracode's site.
Once a file has been uploaded, it will be deleted.
If a network error occurred during upload, re-run this task to continue uploading outstanding files.

* Run `veracodeBeginPreScan`: Perform a pre-scan for the current build.
This task will take some time depending on the number of files being processed.

  - Wait for pre-scan to complete with the `veracodeBuildInfo` task.
  It should return "status=Pre-Scan Success".

* Run `veracodePreScanResults` and `preScanModuleVerify`: Once pre-scan has completed successfully, we need to perform a pre-scan module verification.
This task ensures all modules in pre-scan results are accounted for within the white/black list of modules in `src/apps/${app_id}/modules-*.txt`.
Any unaccounted module should be manually resolved by updating the appropriate `modules-*.txt` file.
Note that `preScanModuleVerify` uses output from the `veracodePreScanResults` task so it must be executed first.
TODO: The whitelist/blacklist needs to be re-worked.

=== Example Sequence of Tasks

Described as Gradle tasks, a typical submission workflow might look like this:

. Download application (manual).

. Install the application so we can scan for files to upload & scan (manual).

. `gradle veracodeCreateBuild -Papp_id=20299 -Pbuild_version="my_product-123"`

. `gradle generateToUpload -Pdir="C:\temp\my_product-123"`

. `gradle veracodeUpload -Papp_id=20299`

. `gradle veracodeBeginPreScan -Papp_id=20299`

. `gradle veracodePreScanResults -Papp_id=20299`
+
NOTE: Must execute veracodePreScanResults before preScanModuleVerify because it uses the former's output

. `gradle preScanModuleVerify -Papp_id=20299`

. `gradle veracodeScan -Papp_id=20299`

. `gradle veracodeScanResults -Pbuild_id=xxxxx`
+
NOTE: Must execute veracodeScanResults before veracodeScanResultsInCsv

. `gradle veracodeScanResultsInCsv -Pbuild_id=xxxxx`

== Veracode Report

This tool provides the ability to generate CSV reports based on scan results for an application.

. Get the _build_id_ of the application you want a report on using the `veracodeBuildList` command.
The last item in the output represents the latest scan.

. Generate the raw CSV flaw report to `build/scan-results.csv` by running the `veracodeScanResults` and `veracodeScanResultsInCsv` tasks in sequence.

. In addition to getting the flaw report, a more specific report that groups flaw by the module that it was reported from can be generated using the `reportFlawsByTeam` command (filtering managed in `teams.json`).
+
This command has multiple modes:
- `action` - Report flaws that require action to be taken.
- `actionSummary` - Similar to `action` mode but more concise.
- `verbose` - List all flaws.

=== Example (Generating Reports)

        C:\github\vt>gradle veracodeBuildList -Papp_id=20299
        :veracodeBuildList
        22792=xxx build #113
        253467=xxx build #2758
        259771=xxx build #2965
        264509=xxx build #3057
        264853=xxx build #3085
        266517=xxx build #3145
        BUILD SUCCESSFUL
        Total time: 12.094 secs

        C:\github\vt>gradle veracodeScanResults veracodeScanResultsInCsv -Pbuild_id=266517
        :veracodeScanResults
        :veracodeScanResultsInCsv
        BUILD SUCCESSFUL
        Total time: 13.105 secs

        C:\github\vt>gradle reportFlawsByTeam -Papp_id=20299 -Pmode=action
        :reportFlawsByTeam
        ...output... (pipe the output to a file for analysis)

TODO: Someone please help implement `reportFlawsDiff`.

== Authentication

Rename `sample-gradle.properties` to `gradle.properties` and enter your Veracode login credentials.

== List Available Tasks

Provide a list of available tasks for this project.

    gradle -q tasks

== Analyze RAW output files

Most Veracode related tasks will generate a relevant `build/xxx.xml` file.
It might be useful to analyze the contents of this file to gain additional insight into the task that was just executed.

== Check Pre-Scan Results

This task is used to check (Note: this task can take some time to complete):

    gradle -q veracodePreScanResults -Papp_id=20299

== Check Build Status

Pre-scan can be time consuming.
To check the status of a build after pre-scan submission, do this:

    gradle -q veracodeBuildInfo -Papp_id=20299
    [Build]
            version=my_product-123
            build_id=123
            submitter=Xxx
            platform=Not Specified
            lifecycle_stage=Xxx
            results_ready=false
            policy_name=Xxx
            policy_version=999
            policy_compliance_status=Xxx
            rules_status=Xxx
            grace_period_expired=false
            scan_overdue=false
    [Analysis Unit]
            analysis_type=Static
            *status=Pre-Scan Submitted*

NOTE: This task can be executed anytime.

== Delete Bad Build

To abandon a build with partially uploaded files or pre-scanned files, execute the delete build task:

    gradle -q veracodeDeleteBuild -Papp_id=20299

== LICENSE

MIT License

Copyright (c) 2017 Calgary Scientific Incorporated

Copyright (c) 2013-2014 kctang

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
